/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicios_todos;

import br.com.jmary.home.Home;
import br.com.jmary.home.jpa.JPAUtil;
import br.com.jmary.utilidades.Exportando;
import br.com.jmary.utilidades.JOPM;
import imagens_internas.Imagens_Internas;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Query;
import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class Exercicios_Indice_Adicao_Leitura_e_Aprendizagem extends javax.swing.JPanel {

    Home Home;
    /**
     * Creates new form Exercicios_00_Portugues_Indice
     * @param Home2
     */
    public Exercicios_Indice_Adicao_Leitura_e_Aprendizagem( Home Home2) {
        Home = Home2;        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbAssunto_1 = new javax.swing.JLabel();
        lbExercicio_1 = new javax.swing.JLabel();
        lbAssunto_2 = new javax.swing.JLabel();
        lbExercicio_2 = new javax.swing.JLabel();
        lbAssunto_3 = new javax.swing.JLabel();
        lbExercicio_3 = new javax.swing.JLabel();
        lbAssunto_5 = new javax.swing.JLabel();
        lbExercicio_5 = new javax.swing.JLabel();
        lbAssunto_6 = new javax.swing.JLabel();
        lbExercicio_6 = new javax.swing.JLabel();
        lbAssunto_7 = new javax.swing.JLabel();
        lbExercicio_7 = new javax.swing.JLabel();
        lbAssunto_8 = new javax.swing.JLabel();
        lbExercicio_8 = new javax.swing.JLabel();
        lbAssunto_9 = new javax.swing.JLabel();
        lbExercicio_9 = new javax.swing.JLabel();
        lbAssunto_10 = new javax.swing.JLabel();
        lbExercicio_10 = new javax.swing.JLabel();
        lbAssunto_11 = new javax.swing.JLabel();
        lbExercicio_11 = new javax.swing.JLabel();
        lbExercicio_12 = new javax.swing.JLabel();
        lbAssunto_12 = new javax.swing.JLabel();
        lbExercicio_4 = new javax.swing.JLabel();
        lbAssunto_4 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Matemática - Adição - Exercícios");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Índice");

        lbAssunto_1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_1.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_1.setText("Matemática > Adição > Definição");
        lbAssunto_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_1MousePressed(evt);
            }
        });

        lbExercicio_1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_1.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_1.setToolTipText("Criar Novo Exercício");
        lbExercicio_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_1MousePressed(evt);
            }
        });

        lbAssunto_2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_2.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_2.setText("Matemática > Adição > História");
        lbAssunto_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_2MousePressed(evt);
            }
        });

        lbExercicio_2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_2.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_2.setToolTipText("Criar Novo Exercício");
        lbExercicio_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_2MousePressed(evt);
            }
        });

        lbAssunto_3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_3.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_3.setText("Matemática > Adição > Algorítimo da Adição");
        lbAssunto_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_3MousePressed(evt);
            }
        });

        lbExercicio_3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_3.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_3.setToolTipText("Criar Novo Exercício");
        lbExercicio_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_3MousePressed(evt);
            }
        });

        lbAssunto_5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_5.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_5.setText("Matemática > Adição > Ordem das Unidades");
        lbAssunto_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_5MousePressed(evt);
            }
        });

        lbExercicio_5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_5.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_5.setToolTipText("Criar Novo Exercício");
        lbExercicio_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_5MousePressed(evt);
            }
        });

        lbAssunto_6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_6.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_6.setText("Matemática > Adição > Ordem das Dezenas");
        lbAssunto_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_6MousePressed(evt);
            }
        });

        lbExercicio_6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_6.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_6.setToolTipText("Criar Novo Exercício");
        lbExercicio_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_6MousePressed(evt);
            }
        });

        lbAssunto_7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_7.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_7.setText("Matemática > Adição > Ordem das Centenas");
        lbAssunto_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_7MousePressed(evt);
            }
        });

        lbExercicio_7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_7.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_7.setToolTipText("Criar Novo Exercício");
        lbExercicio_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_7MousePressed(evt);
            }
        });

        lbAssunto_8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_8.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_8.setText("Matemática > Adição > Classe 2: Unidades de Milhar");
        lbAssunto_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_8MousePressed(evt);
            }
        });

        lbExercicio_8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_8.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_8.setToolTipText("Criar Novo Exercício");
        lbExercicio_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_8MousePressed(evt);
            }
        });

        lbAssunto_9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_9.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_9.setText("Matemática > Adição > Classe 3: Unidades de Milhão");
        lbAssunto_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_9MousePressed(evt);
            }
        });

        lbExercicio_9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_9.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_9.setToolTipText("Criar Novo Exercício");
        lbExercicio_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_9MousePressed(evt);
            }
        });

        lbAssunto_10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_10.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_10.setText("Matemática > Adição > Classe 1: Unidades Simples");
        lbAssunto_10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_10MousePressed(evt);
            }
        });

        lbExercicio_10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_10.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_10.setToolTipText("Criar Novo Exercício");
        lbExercicio_10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_10MousePressed(evt);
            }
        });

        lbAssunto_11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_11.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_11.setText("Matemática > Adição > Propriedades da Adição");
        lbAssunto_11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_11MousePressed(evt);
            }
        });

        lbExercicio_11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_11.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_11.setToolTipText("Criar Novo Exercício");
        lbExercicio_11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_11MousePressed(evt);
            }
        });

        lbExercicio_12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_12.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_12.setToolTipText("Criar Novo Exercício");
        lbExercicio_12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_12MousePressed(evt);
            }
        });

        lbAssunto_12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_12.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_12.setText("Matemática > Adição > Prova dos 9");
        lbAssunto_12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_12MousePressed(evt);
            }
        });

        lbExercicio_4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExercicio_4.setForeground(new java.awt.Color(204, 0, 51));
        lbExercicio_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/duke.png"))); // NOI18N
        lbExercicio_4.setToolTipText("Criar Novo Exercício");
        lbExercicio_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExercicio_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbExercicio_4MousePressed(evt);
            }
        });

        lbAssunto_4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbAssunto_4.setForeground(new java.awt.Color(204, 0, 51));
        lbAssunto_4.setText("Matemática > Adição > Algarismo");
        lbAssunto_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAssunto_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAssunto_4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbExercicio_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAssunto_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAssunto_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbExercicio_9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Índice", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    Exportando Exportando;
    private void lbAssunto_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_1MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_1.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_1MousePressed

    private void lbExercicio_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_1MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_1.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_1MousePressed

    private void lbAssunto_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_2MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_2.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_2MousePressed

    private void lbExercicio_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_2MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_2.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_2MousePressed

    private void lbAssunto_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_3MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_3.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_3MousePressed

    private void lbExercicio_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_3MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_3.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_3MousePressed

    private void lbAssunto_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_5MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_5.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_5MousePressed

    private void lbExercicio_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_5MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_5.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_5MousePressed

    private void lbAssunto_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_6MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_6.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_6MousePressed

    private void lbExercicio_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_6MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_6.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_6MousePressed

    private void lbAssunto_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_7MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_7.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_7MousePressed

    private void lbExercicio_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_7MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_7.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_7MousePressed

    private void lbAssunto_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_8MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_8.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_8MousePressed

    private void lbExercicio_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_8MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_8.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_8MousePressed

    private void lbAssunto_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_9MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_9.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_9MousePressed

    private void lbExercicio_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_9MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_9.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_9MousePressed

    private void lbAssunto_10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_10MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_10.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_10MousePressed

    private void lbExercicio_10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_10MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_10.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_10MousePressed

    private void lbAssunto_11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_11MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_11.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_11MousePressed

    private void lbExercicio_11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_11MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_11.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_11MousePressed

    private void lbExercicio_12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_12MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_12.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_12MousePressed

    private void lbAssunto_12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_12MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_12.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_12MousePressed

    private void lbExercicio_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExercicio_4MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            criar_exercicios( lbAssunto_4.getText().trim() );
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbExercicio_4MousePressed

    private void lbAssunto_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAssunto_4MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
        
            fazer_Exercicios( lbAssunto_4.getText().trim() );        
        } catch( Exception e ){} } }.start();
    }//GEN-LAST:event_lbAssunto_4MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAssunto_1;
    private javax.swing.JLabel lbAssunto_10;
    private javax.swing.JLabel lbAssunto_11;
    private javax.swing.JLabel lbAssunto_12;
    private javax.swing.JLabel lbAssunto_2;
    private javax.swing.JLabel lbAssunto_3;
    private javax.swing.JLabel lbAssunto_4;
    private javax.swing.JLabel lbAssunto_5;
    private javax.swing.JLabel lbAssunto_6;
    private javax.swing.JLabel lbAssunto_7;
    private javax.swing.JLabel lbAssunto_8;
    private javax.swing.JLabel lbAssunto_9;
    private javax.swing.JLabel lbExercicio_1;
    private javax.swing.JLabel lbExercicio_10;
    private javax.swing.JLabel lbExercicio_11;
    private javax.swing.JLabel lbExercicio_12;
    private javax.swing.JLabel lbExercicio_2;
    private javax.swing.JLabel lbExercicio_3;
    private javax.swing.JLabel lbExercicio_4;
    private javax.swing.JLabel lbExercicio_5;
    private javax.swing.JLabel lbExercicio_6;
    private javax.swing.JLabel lbExercicio_7;
    private javax.swing.JLabel lbExercicio_8;
    private javax.swing.JLabel lbExercicio_9;
    // End of variables declaration//GEN-END:variables

    private void fazer_Exercicios(String assunto_recebido) {                                         
        /*new Thread() {   @Override public void run() {*/ try { Thread.sleep( 1 );
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
            
            boolean criar_Exercicios = false;
            
            int numeroExercicio = 0;            
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            
            int intCerto = 0;
            int intErrado = 0;
            ////////////////
            numeroExercicio++;
            String nome_do_tab_exercicio = "Exercicio - " + numeroExercicio;
            
            ///////////////////////////////////////
            List<br.com.jmary.home.beans.Exercicios> Exercicios_Beans = null;
            try{
                Query q = JPAUtil.em().createNativeQuery( "SELECT * FROM JM.EXERCICIOS WHERE ASSUNTO = ?", br.com.jmary.home.beans.Exercicios.class );
                q.setParameter(1, assunto_recebido.toUpperCase() );
                Exercicios_Beans = q.getResultList();
            }catch(Exception e ){} 
            
            String rbusca = ""; try{ rbusca = Exercicios_Beans.get(0).getPergunta(); }catch( Exception e ){}
            
            if( !rbusca.equals("") ){
                List<Integer> lista_Ids = new ArrayList<Integer>();
                for (int i = 0; i < Exercicios_Beans.size(); i++){
                    
                    lista_Ids.add( Exercicios_Beans.get(i).getId() );
                }
                
                int id_atual = Exercicios_Beans.get(0).getId();
                
                /////////////////////////////////////////////////////////////////////////////////////////
                Exercicios_Beans.get(0).setAssunto( assunto_recebido.toUpperCase() );
            
                Class Class_Ajuda_Interna = null; try{ Class_Ajuda_Interna = Exercicios_Beans.get(0).getClass(); }catch( Exception e){}                              
                /////////////////////////////////////////////////////////////////////////////////////////           
                Home.ControleTabs.removerTabSelecionado();
                Home.ControleTabs.AddTabSemSCControleNovo( nome_do_tab_exercicio, "/imagens_internas/livroTp.gif", 
                    new Exercicios( Home, 
                            intCerto, intErrado, numeroExercicio,
                            Class_Ajuda_Interna, Exercicios_Beans.get(0),
                            criar_Exercicios,
                            lista_Ids, id_atual
                    ) );            
            }
            else{
                
                Class<Imagens_Internas> clazzHome = Imagens_Internas.class;
                JOPM JOptionPaneMod = new JOPM( 1, "SEM EXERCÍCIOS\n"
                    + "\nSTATUS: "
                    + "\nNÃO HÁ EXERCÍCIOS CADASTRADOS PARA"
                    + "\n"+assunto_recebido.toUpperCase() 
                    ,"SEM EXERCÍCIOS", 
                new ImageIcon( clazzHome.getResource("logocangaco2.png")) );
            }

            Exportando.fechar();
        } catch( Exception e ){ Exportando.fechar(); e.printStackTrace(); } //} }.start();
    }
    
    private void criar_exercicios(String assunto_recebido) {                                   
        /*new Thread() {   @Override public void run() {*/ try { Thread.sleep( 1 );
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
            
            boolean criar_Exercicios = true;
            
            int numeroExercicio = 0;            
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            
            List<Integer> lista_Ids = null;
            int id_atual = 0;     
            
            int intCerto = 0;
            int intErrado = 0;
            ////////////////
            numeroExercicio++;
            String nome_do_tab_exercicio = "Criar Exercicios";
            
            br.com.jmary.home.beans.Exercicios Exercicios_Beans = new br.com.jmary.home.beans.Exercicios();
            Exercicios_Beans.setAssunto( assunto_recebido.toUpperCase() );
            
            Class Class_Ajuda_Interna = null;                                
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////           
            Home.ControleTabs.removerTabSelecionado();
            Home.ControleTabs.AddTabSemSCControleNovo( nome_do_tab_exercicio, "/imagens_internas/livroTp.gif", 
                new Exercicios( Home, 
                        intCerto, intErrado, numeroExercicio,
                        Class_Ajuda_Interna, Exercicios_Beans,
                        criar_Exercicios,
                        lista_Ids, id_atual
                ) );

            Exportando.fechar();
        } catch( Exception e ){ Exportando.fechar(); e.printStackTrace(); } //} }.start();
    }
}
